# Generated by Django 3.1.3 on 2020-12-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorturls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
